### ISSUE TITLE
ReferenceError: ErrorUtils is not defined

### ISSUE THREAD

**Issue by karapish** [Milvasoft/expo-boilerplate#2]
Hello!

I would like to use your nice boilerplate for my expo app. But I'm running into an issue testing your repo code.

Steps
=-=-=-
1) I cloned your repo.
2) Ran 'expo install'
3) Ran 'expo start:web'
![image](https://user-images.githubusercontent.com/9142734/164677195-afe78a51-56e4-4ca3-87ba-20ab3800a331.png)

4) Opened http://172.20.10.5:19006/ with Chrome  

Expected
-=-=-=-=-=-
To see some UI / UX

Actual
=-==-=-=-
1) Getting the blank screen in Chrome. 

Troubleshooting
-=-=-=-=-=-=-=
1) DevTools shows the following errors in the console spew
<img width="491" alt="image" src="https://user-images.githubusercontent.com/9142734/164677370-b8ec2908-4ec8-46ac-b3d0-9933d7ed101c.png">

2) It seems the runtime can't reference ErrorUtils 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/9142734/164676274-3f7caad9-ef65-46dd-ad16-ddee532d29d8.png">

Best wishes,
Gleb

**Comment by aliburhankeskin** [comment]
Hello @karapish ,

I'm glad you like expo-boilerplate.😊

I'm dealing with the bug right now.

Best wishes
